package com.bitbi.dfm.contract;

import com.bitbi.dfm.config.TestSecurityConfig;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.test.web.servlet.MockMvc;

import static org.hamcrest.Matchers.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Contract tests for Site Management User API.
 * <p>
 * Tests the /api/sites endpoints for user site management (US1).
 * </p>
 *
 * Feature: 007-adding-a-site (T025-T026, US1)
 */
@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
@Import(TestSecurityConfig.class)
@Sql("/test-data.sql")
@DisplayName("Site Management User API Contract Tests")
class SiteContractTest {

    @Autowired
    private MockMvc mockMvc;

    private static final String SITES_ENDPOINT = "/api/sites";
    private static final String MOCK_JWT_HEADER = "Bearer mock-jwt-token-account-1";

    /**
     * T025: Test Case 1 - Create site with custom password.
     * <p>
     * Given: Authenticated user with valid domain and password
     * When: POST /api/sites with domain and password
     * Then: 201 Created with site details and password
     * </p>
     */
    @Test
    @DisplayName("TC01: Should create site with custom password")
    void shouldCreateSiteWithCustomPassword() throws Exception {
        String requestBody = """
            {
                "domain": "test-site-custom.com",
                "displayName": "Test Site Custom",
                "password": "Pass1234"
            }
            """;

        mockMvc.perform(post(SITES_ENDPOINT)
                        .header("Authorization", MOCK_JWT_HEADER)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(requestBody))
                .andExpect(status().isCreated())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.site").exists())
                .andExpect(jsonPath("$.site.id").exists())
                .andExpect(jsonPath("$.site.domain").value("test-site-custom.com"))
                .andExpect(jsonPath("$.site.name").value("Test Site Custom"))
                .andExpect(jsonPath("$.site.isActive").value(true))
                .andExpect(jsonPath("$.password").value("Pass1234"));
    }

    /**
     * T025: Test Case 2 - Create site with auto-generated password.
     * <p>
     * Given: Authenticated user with valid domain, no password
     * When: POST /api/sites with domain only
     * Then: 201 Created with generated 8-12 char alphanumeric password
     * </p>
     */
    @Test
    @DisplayName("TC02: Should create site with auto-generated password")
    void shouldCreateSiteWithAutoGeneratedPassword() throws Exception {
        String requestBody = """
            {
                "domain": "test-site-auto.com",
                "displayName": "Test Site Auto"
            }
            """;

        mockMvc.perform(post(SITES_ENDPOINT)
                        .header("Authorization", MOCK_JWT_HEADER)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(requestBody))
                .andExpect(status().isCreated())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.site").exists())
                .andExpect(jsonPath("$.site.domain").value("test-site-auto.com"))
                .andExpect(jsonPath("$.password").exists())
                .andExpect(jsonPath("$.password").isString())
                .andExpect(jsonPath("$.password", hasLength(greaterThanOrEqualTo(8))))
                .andExpect(jsonPath("$.password", hasLength(lessThanOrEqualTo(12))))
                .andExpect(jsonPath("$.password", matchesPattern("^[a-zA-Z0-9]+$")));
    }

    /**
     * T025: Test Case 3 - Reject duplicate domain for same account.
     * <p>
     * Given: User tries to create site with existing domain
     * When: POST /api/sites with duplicate domain
     * Then: 409 Conflict
     * </p>
     */
    @Test
    @DisplayName("TC03: Should reject duplicate domain for same account")
    void shouldRejectDuplicateDomainForSameAccount() throws Exception {
        // First create a site
        String requestBody = """
            {
                "domain": "duplicate-test.com",
                "displayName": "Duplicate Test"
            }
            """;

        mockMvc.perform(post(SITES_ENDPOINT)
                        .header("Authorization", MOCK_JWT_HEADER)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(requestBody))
                .andExpect(status().isCreated());

        // Try to create duplicate
        mockMvc.perform(post(SITES_ENDPOINT)
                        .header("Authorization", MOCK_JWT_HEADER)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(requestBody))
                .andExpect(status().isConflict())
                .andExpect(jsonPath("$.message", containsString("already exists")));
    }

    /**
     * T025: Test Case 4 - Validate domain format.
     * <p>
     * Given: Invalid domain format
     * When: POST /api/sites with invalid domain
     * Then: 400 Bad Request
     * </p>
     */
    @Test
    @DisplayName("TC04: Should reject invalid domain format")
    void shouldRejectInvalidDomainFormat() throws Exception {
        String requestBody = """
            {
                "domain": "INVALID-DOMAIN",
                "displayName": "Invalid Domain"
            }
            """;

        mockMvc.perform(post(SITES_ENDPOINT)
                        .header("Authorization", MOCK_JWT_HEADER)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(requestBody))
                .andExpect(status().isBadRequest());
    }

    /**
     * T026: Test Case 5 - List user's sites.
     * <p>
     * Given: User has created sites
     * When: GET /api/sites
     * Then: 200 OK with list of sites sorted by createdAt desc
     * </p>
     */
    @Test
    @DisplayName("TC05: Should list user's sites sorted by creation date")
    void shouldListUsersSitesSortedByCreationDate() throws Exception {
        // Create two sites
        String site1 = """
            {
                "domain": "first-site.com",
                "displayName": "First Site"
            }
            """;

        String site2 = """
            {
                "domain": "second-site.com",
                "displayName": "Second Site"
            }
            """;

        mockMvc.perform(post(SITES_ENDPOINT)
                .header("Authorization", MOCK_JWT_HEADER)
                .contentType(MediaType.APPLICATION_JSON)
                .content(site1));

        Thread.sleep(100); // Ensure different timestamps

        mockMvc.perform(post(SITES_ENDPOINT)
                .header("Authorization", MOCK_JWT_HEADER)
                .contentType(MediaType.APPLICATION_JSON)
                .content(site2));

        // List sites
        mockMvc.perform(get(SITES_ENDPOINT)
                        .header("Authorization", MOCK_JWT_HEADER))
                .andExpect(status().isOk())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$").isArray())
                .andExpect(jsonPath("$", hasSize(greaterThanOrEqualTo(2))))
                .andExpect(jsonPath("$[0].domain").value("second-site.com")) // Most recent first
                .andExpect(jsonPath("$[1].domain").value("first-site.com"));
    }

    /**
     * T026: Test Case 6 - Unauthenticated request rejected.
     * <p>
     * Given: No authentication token
     * When: GET /api/sites without token
     * Then: 401 Unauthorized
     * </p>
     */
    @Test
    @DisplayName("TC06: Should reject unauthenticated requests")
    void shouldRejectUnauthenticatedRequests() throws Exception {
        mockMvc.perform(get(SITES_ENDPOINT))
                .andExpect(status().isUnauthorized());
    }
}
