spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging:
  level:
    root: INFO
    com.bitbi.dfm: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
