spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dfm
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

s3:
  endpoint: http://localhost:4566
  region: us-east-1
  bucket-name: data-forge-dev-bucket
  access-key: test
  secret-key: test
  path-style-access-enabled: true

keycloak:
  auth-server-url: http://localhost:8081
  credentials:
    secret: dev-client-secret

logging:
  level:
    root: INFO
    com.bitbi.dfm: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
