apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge-backend
  namespace: forge
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: "300m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "1536Mi"
      topologySpreadConstraints: []
