package com.bitbi.dfm.account.presentation.dto;

import com.bitbi.dfm.account.domain.Account;

import java.time.Instant;
import java.util.UUID;

/**
 * Response DTO for account.
 * <p>
 * This DTO is returned when creating or listing accounts.
 * Includes authentication user ID and temporary password (for create operations only).
 * </p>
 *
 * User Story: US1 - Admin Creates User Account
 *
 * @param id The account's unique identifier (PostgreSQL UUID)
 * @param email The user's email address
 * @param name The user's full name
 * @param phone The user's phone number (nullable)
 * @param company The user's company name (nullable)
 * @param isActive Whether the account is active
 * @param identityProviderUserId The identity provider user ID (e.g., auth0|{id})
 * @param temporaryPassword Temporary password for first login (only present on create, null on list)
 * @param passwordResetUrl URL for password reset (alternative to temporaryPassword)
 * @param createdAt Account creation timestamp
 *
 * @author Data Forge Team
 * @version 1.0.0
 */
public record AccountResponseDto(
    UUID id,
    String email,
    String name,
    String phone,
    String company,
    boolean isActive,
    String identityProviderUserId,
    String temporaryPassword,
    String passwordResetUrl,
    Instant createdAt
) {
    /**
     * Factory method to create response from Account entity (without temporary password).
     * Used for list operations.
     *
     * @param account The account entity
     * @return Response DTO
     */
    public static AccountResponseDto fromEntity(Account account) {
        return new AccountResponseDto(
            account.getId(),
            account.getEmail(),
            account.getName(),
            account.getPhone() != null ? account.getPhone().getValue() : null,
            account.getCompany() != null ? account.getCompany().getValue() : null,
            account.getIsActive(),
            account.getIdentityProviderUserId(),
            null, // No temporary password for list operations
            null, // No password reset URL for list operations
            Instant.ofEpochSecond(account.getCreatedAt().toEpochSecond(java.time.ZoneOffset.UTC))
        );
    }

    /**
     * Factory method to create response from Account entity with temporary password.
     * Used for create operations.
     *
     * @param account The account entity
     * @param temporaryPassword The temporary password generated by Auth0
     * @return Response DTO with temporary password
     */
    public static AccountResponseDto fromEntityWithPassword(
        Account account,
        String temporaryPassword
    ) {
        return new AccountResponseDto(
            account.getId(),
            account.getEmail(),
            account.getName(),
            account.getPhone() != null ? account.getPhone().getValue() : null,
            account.getCompany() != null ? account.getCompany().getValue() : null,
            account.getIsActive(),
            account.getIdentityProviderUserId(),
            temporaryPassword,
            null, // No URL when returning temporary password
            Instant.ofEpochSecond(account.getCreatedAt().toEpochSecond(java.time.ZoneOffset.UTC))
        );
    }

    /**
     * Factory method to create response from Account entity with password reset URL.
     * Used for create operations with Auth0 password change tickets.
     *
     * @param account The account entity
     * @param passwordResetUrl The Auth0 password reset URL
     * @return Response DTO with password reset URL
     */
    public static AccountResponseDto fromEntityWithResetUrl(
        Account account,
        String passwordResetUrl
    ) {
        return new AccountResponseDto(
            account.getId(),
            account.getEmail(),
            account.getName(),
            account.getPhone() != null ? account.getPhone().getValue() : null,
            account.getCompany() != null ? account.getCompany().getValue() : null,
            account.getIsActive(),
            account.getIdentityProviderUserId(),
            null, // No temporary password when returning URL
            passwordResetUrl,
            Instant.ofEpochSecond(account.getCreatedAt().toEpochSecond(java.time.ZoneOffset.UTC))
        );
    }
}
